# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'satismeter-swiftui-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "SatisMeter", "0.4.1"

end
