source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SatisMeter_Example', :exclusive => true do
  pod 'SatisMeter'
end

target 'SatisMeter_Tests', :exclusive => true do
  pod 'SatisMeter'

  
end
